/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
      },
      dropShadow: {
        glow: '0 0 10px rgba(255, 255, 255, 0.5)',
        'glow-primary': '0 0 15px var(--color-primary)',
      },
      colors: {
        light: {
          bg: '#FAFAFA',
          surface: '#FFFFFF',
          primary: '#2563EB',
          secondary: '#64748B',
          accent: '#3B82F6',
          text: {
            primary: '#0F172A',
            secondary: '#475569',
            tertiary: '#94A3B8',
          },
        },
        "surface-container-highest": "#262626",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-fixed": "#49494b",
        "on-secondary-fixed-variant": "#5b5b60",
        "outline": "#767575",
        "on-tertiary-container": "#575658",
        "tertiary-container": "#eceaec",
        "primary-dim": "#b8b9b9",
        "on-error": "#490106",
        "surface-container-lowest": "#000000",
        "on-background": "#e7e5e4",
        "primary-container": "#454747",
        "primary-fixed-dim": "#d4d4d4",
        "outline-variant": "#484848",
        "surface-container": "#1a1919",
        "secondary": "#9d9da2",
        "tertiary": "#fbf9fb",
        "tertiary-dim": "#eceaec",
        "surface-container-low": "#131313",
        "secondary-fixed-dim": "#d5d4d9",
        "on-tertiary": "#5f5f61",
        "surface-tint": "#c6c6c7",
        "secondary-container": "#3a3b3f",
        "on-secondary": "#1f2024",
        "on-tertiary-fixed-variant": "#666668",
        "error": "#ee7d77",
        "primary-fixed": "#e2e2e2",
        "on-surface": "#e7e5e4",
        "tertiary-fixed": "#f5f3f5",
        "on-error-container": "#ff9993",
        "error-container": "#7f2927",
        "surface-bright": "#2c2c2c",
        "surface-variant": "#262626",
        "on-secondary-container": "#bfbfc4",
        "on-secondary-fixed": "#3e3f43",
        "on-primary-fixed": "#3e4040",
        "inverse-on-surface": "#565554",
        "secondary-fixed": "#e3e2e7",
        "surface-container-high": "#202020",
        "background": "#0e0e0e",
        "on-primary-container": "#d0d0d0",
        "inverse-primary": "#5e5f60",
        "error-dim": "#bb5551",
        "secondary-dim": "#9d9da2",
        "on-primary": "#3f4041",
        "tertiary-fixed-dim": "#e7e5e7",
        "surface-dim": "#0e0e0e",
        "on-surface-variant": "#acabaa",
        "surface": "#0e0e0e",
        "on-primary-fixed-variant": "#5a5c5c",
        "primary": "#c6c6c7"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Lexend', 'Inter', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
